
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hci3_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hci3_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  
stage:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hci3_stage
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hci3_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
